// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GSProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GSProtocol.proto</summary>
public static partial class GSProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for GSProtocol.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GSProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBHU1Byb3RvY29sLnByb3RvGhBDb25uZWN0aW9uLnByb3RvIlYKEEdTV3Jh",
          "cHBlclJlcXVlc3QSNwoSY29ubmVjdGlvbl9yZXF1ZXN0GAEgASgLMhkuQ29u",
          "bmVjdGlvblJlcXVlc3RXcmFwcGVySABCCQoHcmVxdWVzdCJaChFHU1dyYXBw",
          "ZXJSZXNwb25zZRI5ChNjb25uZWN0aW9uX3Jlc3BvbnNlGAEgASgLMhouQ29u",
          "bmVjdGlvblJlc3BvbnNlV3JhcHBlckgAQgoKCHJlc3BvbnNlYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ConnectionReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GSWrapperRequest), global::GSWrapperRequest.Parser, new[]{ "ConnectionRequest" }, new[]{ "Request" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GSWrapperResponse), global::GSWrapperResponse.Parser, new[]{ "ConnectionResponse" }, new[]{ "Response" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GSWrapperRequest : pb::IMessage<GSWrapperRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GSWrapperRequest> _parser = new pb::MessageParser<GSWrapperRequest>(() => new GSWrapperRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GSWrapperRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GSProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GSWrapperRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GSWrapperRequest(GSWrapperRequest other) : this() {
    switch (other.RequestCase) {
      case RequestOneofCase.ConnectionRequest:
        ConnectionRequest = other.ConnectionRequest.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GSWrapperRequest Clone() {
    return new GSWrapperRequest(this);
  }

  /// <summary>Field number for the "connection_request" field.</summary>
  public const int ConnectionRequestFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ConnectionRequestWrapper ConnectionRequest {
    get { return requestCase_ == RequestOneofCase.ConnectionRequest ? (global::ConnectionRequestWrapper) request_ : null; }
    set {
      request_ = value;
      requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.ConnectionRequest;
    }
  }

  private object request_;
  /// <summary>Enum of possible cases for the "request" oneof.</summary>
  public enum RequestOneofCase {
    None = 0,
    ConnectionRequest = 1,
  }
  private RequestOneofCase requestCase_ = RequestOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RequestOneofCase RequestCase {
    get { return requestCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRequest() {
    requestCase_ = RequestOneofCase.None;
    request_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GSWrapperRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GSWrapperRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ConnectionRequest, other.ConnectionRequest)) return false;
    if (RequestCase != other.RequestCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (requestCase_ == RequestOneofCase.ConnectionRequest) hash ^= ConnectionRequest.GetHashCode();
    hash ^= (int) requestCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (requestCase_ == RequestOneofCase.ConnectionRequest) {
      output.WriteRawTag(10);
      output.WriteMessage(ConnectionRequest);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (requestCase_ == RequestOneofCase.ConnectionRequest) {
      output.WriteRawTag(10);
      output.WriteMessage(ConnectionRequest);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (requestCase_ == RequestOneofCase.ConnectionRequest) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectionRequest);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GSWrapperRequest other) {
    if (other == null) {
      return;
    }
    switch (other.RequestCase) {
      case RequestOneofCase.ConnectionRequest:
        if (ConnectionRequest == null) {
          ConnectionRequest = new global::ConnectionRequestWrapper();
        }
        ConnectionRequest.MergeFrom(other.ConnectionRequest);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::ConnectionRequestWrapper subBuilder = new global::ConnectionRequestWrapper();
          if (requestCase_ == RequestOneofCase.ConnectionRequest) {
            subBuilder.MergeFrom(ConnectionRequest);
          }
          input.ReadMessage(subBuilder);
          ConnectionRequest = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::ConnectionRequestWrapper subBuilder = new global::ConnectionRequestWrapper();
          if (requestCase_ == RequestOneofCase.ConnectionRequest) {
            subBuilder.MergeFrom(ConnectionRequest);
          }
          input.ReadMessage(subBuilder);
          ConnectionRequest = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GSWrapperResponse : pb::IMessage<GSWrapperResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GSWrapperResponse> _parser = new pb::MessageParser<GSWrapperResponse>(() => new GSWrapperResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GSWrapperResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GSProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GSWrapperResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GSWrapperResponse(GSWrapperResponse other) : this() {
    switch (other.ResponseCase) {
      case ResponseOneofCase.ConnectionResponse:
        ConnectionResponse = other.ConnectionResponse.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GSWrapperResponse Clone() {
    return new GSWrapperResponse(this);
  }

  /// <summary>Field number for the "connection_response" field.</summary>
  public const int ConnectionResponseFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ConnectionResponseWrapper ConnectionResponse {
    get { return responseCase_ == ResponseOneofCase.ConnectionResponse ? (global::ConnectionResponseWrapper) response_ : null; }
    set {
      response_ = value;
      responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.ConnectionResponse;
    }
  }

  private object response_;
  /// <summary>Enum of possible cases for the "response" oneof.</summary>
  public enum ResponseOneofCase {
    None = 0,
    ConnectionResponse = 1,
  }
  private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ResponseOneofCase ResponseCase {
    get { return responseCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearResponse() {
    responseCase_ = ResponseOneofCase.None;
    response_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GSWrapperResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GSWrapperResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ConnectionResponse, other.ConnectionResponse)) return false;
    if (ResponseCase != other.ResponseCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (responseCase_ == ResponseOneofCase.ConnectionResponse) hash ^= ConnectionResponse.GetHashCode();
    hash ^= (int) responseCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (responseCase_ == ResponseOneofCase.ConnectionResponse) {
      output.WriteRawTag(10);
      output.WriteMessage(ConnectionResponse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (responseCase_ == ResponseOneofCase.ConnectionResponse) {
      output.WriteRawTag(10);
      output.WriteMessage(ConnectionResponse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (responseCase_ == ResponseOneofCase.ConnectionResponse) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectionResponse);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GSWrapperResponse other) {
    if (other == null) {
      return;
    }
    switch (other.ResponseCase) {
      case ResponseOneofCase.ConnectionResponse:
        if (ConnectionResponse == null) {
          ConnectionResponse = new global::ConnectionResponseWrapper();
        }
        ConnectionResponse.MergeFrom(other.ConnectionResponse);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::ConnectionResponseWrapper subBuilder = new global::ConnectionResponseWrapper();
          if (responseCase_ == ResponseOneofCase.ConnectionResponse) {
            subBuilder.MergeFrom(ConnectionResponse);
          }
          input.ReadMessage(subBuilder);
          ConnectionResponse = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::ConnectionResponseWrapper subBuilder = new global::ConnectionResponseWrapper();
          if (responseCase_ == ResponseOneofCase.ConnectionResponse) {
            subBuilder.MergeFrom(ConnectionResponse);
          }
          input.ReadMessage(subBuilder);
          ConnectionResponse = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
